cd /home/kyang/SCAD_MCP/LM/
sbatch *.sh
cd /home/kyang/SCAD_MCP/logistic/
sbatch *.sh
cd /home/kyang/tasks/task1/
sbatch *.sh
cd /home/kyang/tasks/task2/
sbatch *.sh
cd /home/kyang/tasks/task1speed/
sbatch *.sh
cd /home/kyang/tasks/task2speed/sub_tasks/task2speed_SCAD_coord_time/
sbatch *.sh
cd /home/kyang/tasks/task2speed/sub_tasks/task2speed_MCP_coord_time/
sbatch *.sh
cd /home/kyang/tasks/task2speed/sub_tasks/task2speed_SCAD_AG_time/
sbatch *.sh
cd /home/kyang/tasks/task2speed/sub_tasks/task2speed_MCP_AG_time/
sbatch *.sh
cd /home/kyang/tasks/task2speed/sub_tasks/task2speed_SCAD/
sbatch *.sh
cd /home/kyang/tasks/task2speed/sub_tasks/task2speed_MCP/
sbatch *.sh
cd /home/kyang/
